sudo: required
dist: bionic
branches:
  except:
    - "/\\+travis\\d+$/"

before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-xetex lmodern
script:
- mkdir _build
- xelatex -interaction=nonstopmode -halt-on-error -output-directory _build Resume.tex
- mv _build/Resume.pdf ResumeBLACK.pdf
- xelatex -interaction=nonstopmode -halt-on-error -output-directory _build "\def\iscolor{1}
  \input{Resume.tex}"
- mv _build/Resume.pdf ResumeCOLOR.pdf

after_success:
  - git status
  - pwd
  - ls
  - sh ./t_push.sh
deploy:
  provider: releases
  api_key:
    secure: M21Zd0mZlCQ54qZzjNXXqeI/lH5FRQ34t0Lwi5rugslbC5GdWsWWeyMo6ssDrTUOlNCcSGUDkT9geOFoyWI3+DfkrbNN3nY0wTpW/2ZvXhs3rxAJxfoiwQtNn92jYTZ3zDrcX+/5lzHDOKinPFZLP9hQowE8URIHO4w21Eyf1tTM5mfjxcuiVrIPgsZj1HuFzoRk5GhjufiI2a6IVh99iopRTfMkarpmoYkEN65MKgUY1KNT655DoO+8k2aEJTWEtb117hkIcdFlb9xE8xRWQT/PqXQtq6A7QlJj9KIjjsexXTk2A1oMeK6qbne+6w5O+CyiDv3x/8pDKaqseK5cou5g5dcw2t7cgQaOHvcsMYHxR7ZwbdIo9Fl2Zf4V+jGozN0LjIA20vfMeJrA52Nz7+Sg0kaAnsSfGC4QrdvNY0ExFt8RUmlXTgq578ND8dISHfQVB8sEU6AfCQ6nLxsfk0R6GtODc1jaV6w5HPPvgPSDzWow2n2ZEUaBMYkHRo0IFpHIDKjFJUTcQoJfGFa3EKmSHc5zC8mYdC579T1LzMe0IbEa8ak+8pWR96Vx6yspHLm/fp5KINVrwruQSXj8+GU0AlqmxfYPx+32QE13HkN9GWvnpNWtTp1r1uHMHaM6bj+ztqjk8mIWj43YzITttc3rw/iVi3nvWbhHjxNcMCY=
  skip_cleanup: true
  on:
    repo: andreweggleston/cv
    tags: true
